export const ACTIONS = {
  ADD_PROFILE: "ADD_PROFILE",
  ADD_ABOUT_ME: "ADD_ABOUT_ME",
  ADD_WORK_EXPERIENCE: "ADD_WORK_EXPERIENCE",
  ADD_EDUCATION: "ADD_EDUCATION",
  ADD_HONOR: "ADD_HONOR",
  ADD_CERTIFICATES: "ADD_CERTIFICATES",
  ADD_SKILL: "ADD_SKILL",
  ADD_HOBBIE: "ADD_HOBBIE",
  ADD_LANGUAGE: "ADD_LANGUAGE",
  ADD_PROJECT: "ADD_PROJECT",
  SELECT_TEMPLATE: "SELECT_TEMPLATE",
  SELECT_COLORS: "SELECT_COLORS",
  SELECT_FONT: "SELECT_FONT",
};

export const DRAG_DROP = {
  DRAG_DROP_WORK_EXPERIENCE: "DRAG_DROP_WORK_EXPERIENCE",
  DRAG_DROP_EDUCATION: "DRAG_DROP_EDUCATION",
  DRAG_DROP_HONORS: "DRAG_DROP_HONORS",
  DRAG_DROP_CERTIFICATIONS: "DRAG_DROP_CERTIFICATIONS",
  DRAG_DROP_SKILLS: "DRAG_DROP_SKILLS",
  DRAG_DROP_HOBBIES: "DRAG_DROP_HOBBIES",
  DRAG_DROP_LANGUAGES: "DRAG_DROP_LANGUAGES",
  DRAG_DROP_PROJECTS: "DRAG_DROP_PROJECTS",
};

export const DELETE = {
  WORK_EXPERIENCE: "WORK_EXPERIENCE",
  EDUCATION: "EDUCATION",
  HONORS: "HONORS",
  CERTIFICATIONS: "CERTIFICATIONS",
  SKILL: "SKILL",
  HOBBY:"HOBBY",
  LANGUAGE:"LANGUAGE",
  PROJECT:"PROJECT",
};
