import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/MainPage.module.css";
import { Avatar, Typography } from "@mui/material";
import Image from "next/image";

function Home() {
  // const [width, setWidth] = React.useState("1000");
  // React.useEffect(() => {
  //   setWidth(window.innerWidth);
  // }, [width]);

  // if(width <= "1000"){
  //   return <Typography variant="h5" sx={{textAlign:"center", color:"#5f0aa8",position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%)"}}>Website currently works only on Desktop view</Typography>
  // }
  return (
    <div>
      <Head>
        <title>MPR Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbar}>
        <div className={styles.logo}>
          <Link href="/" passHref>
            <Avatar
              src="/logo1.png"
              alt="navbar_profile"
              sx={{ width: 50, height: 50 }}
            />
          </Link>
          <Link href="/" passHref>
            <Typography variant="h5" sx={{ marginLeft: "1rem" }}>
              MPR Resume Builder
            </Typography>
          </Link>
        </div>
        <div className={styles.links}>
          <Link href="/cover-letters">
            <a className={styles.link}>Cover Letters</a>
          </Link>
          <Link href="/about">
            <a className={styles.link}>About</a>
          </Link>
          <Link href="https://phanindra-reddy.github.io/react-portfolio/">
            <a target="_blank" className={styles.link}>
              Portfolio
            </a>
          </Link>
        </div>
      </div>
      <div className={styles.main}>
        <div>
          <Typography variant="h4" sx={{ marginBottom: "2rem" }}>
            Single Page
            <br />
            Resume Builder
          </Typography>
          <Link href="/editor">
            <a className={styles.button}>Get started</a>
          </Link>
        </div>
        <div>
          <Image src="/logo5.svg" alt="resume-image" width={300} height={300} />
        </div>
      </div>
      <div className={styles.cards}>
        <div className={styles.card}>
          <Avatar
            src="/logo2.png"
            alt="navbar_profile"
            sx={{ width: 50, height: 50 }}
            variant="square"
          />
          <Typography variant="h5" sx={{ color: "#6C63FF" }}>
            No signup/signin
          </Typography>
          <Typography variant="subtitle2">
            Completely free and open source. No registration required. We do not
            store any of your information. Create unlimited resumes using our
            tool.
          </Typography>
        </div>
        <div className={styles.card}>
          <Avatar
            src="/logo3.png"
            alt="navbar_profile"
            sx={{ width: 50, height: 50 }}
            variant="square"
          />
          <Typography variant="h5" sx={{ color: "#6C63FF" }}>
            Build in minutes
          </Typography>
          <Typography variant="subtitle2">
            With the powerful editor and wide range of professinal/job ready
            templates, you can build your resume within a matter few clicks
            &amp; key strokes.
          </Typography>
        </div>
        <div className={styles.card}>
          <Avatar
            src="/logo4.png"
            alt="navbar_profile"
            sx={{ width: 50, height: 50 }}
            variant="square"
          />
          <Typography variant="h5" sx={{ color: "#6C63FF" }}>
            Fit for your needs
          </Typography>
          <Typography variant="subtitle2">
            If you are a developer, customize the template which suits your data
            and all you need to know is some basic knowledge of React and
            programming.
          </Typography>
        </div>
      </div>
    </div>
  );
}

export default Home;
